# Generated by Django 5.1.7 on 2025-03-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='form_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genericform',
            name='service',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
