# Generated by Django 5.1.7 on 2025-03-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_services', '0002_service_form_name_alter_genericform_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genericform',
            options={'verbose_name_plural': 'Service Forms'},
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
